sudo: false
git:
  depth: false
jobs:
  include:
    - stage: Tests
      name: Unit Tests
      language: elixir
      elixir:
        - 1.7
      otp_release:
        - 21.0
      cache:
        directories:
          - _build
          - deps
          - assets/node_modules
          - nodejs/node_modules
      addons:
        postgresql: '9.6'
      services:
        - postgresql
      before_script:
        - gem install coveralls-multi
        - psql -c 'create database incentivize_test;' -U postgres
        - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd
          ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh
          && nvm install 10
      install:
        - mix local.hex --force
        - mix local.rebar --force
        - mix deps.get
        - cd assets
        - npm install
        - cd ..
        - cd priv/nodejs
        - npm install
        - cd ../..
      script:
        - mix coveralls.json
        - cd assets
        - npm test
        - cd ..
        - coveralls-multi
    - stage: deploy
      name: Deploy
      script: skip
      deploy:
        - provider: deis
          controller: deis.prod.revelry.net
          app: incentivize-staging
          cli_version: v2.19.4
          username: '$DEIS_USERNAME'
          password: '$DEIS_PASSWORD'
          on:
            branch: master
        - provider: deis
          controller: deis.prod.revelry.net
          app: incentivize
          cli_version: v2.19.4
          username: '$DEIS_USERNAME'
          password: '$DEIS_PASSWORD'
          on:
            tags: true
      after_deploy:
        - ./deis run "_build/prod/rel/incentivize/bin/incentivize migrate" -a incentivize
notifications:
  slack:
    secure: A+T1wks8KiRVzxoSSgXCwTChB2xZ7AKep1dS/rHEjG9ZY1oq+albynV6UNKVdbv1kr9uxxffrjH/MFT+z6Q9JkS+21n+nEOghhtQHk4VDin+nEGgmMSpBfvePM7Mqe8lo079JYdXhao2yQW6A2XuXYTxjukbC6nl7FhZW3c6yuw50qUjdlzGzlQSh4rCHXPXwyLHcFLJ/cDH+W1v4dMemy+SCa/KhvQAEk63nyRlo1yMta82iY0hQb2E+3xj41/t+LBNT8Q9UPPupO4P/hMnSE9gYQJjsZkiGgznUFPojjB8wPdj94wJ9E/4fOPb0Wk2dMTXROtJ4PAoCW5dL0Y4Bhwc1XnlOxleiSkQgg6IniTTAFuPps3YreMmXb0qapDClplbQZuqxwDuGHK2eTDwGAsd2DAvAcjxyKsYdNZb66FRaJDo/URDuTcyiK/PJQlAFmFH+Iov6R/MVDrv393wrNaU8NY2+U8/dP+ubaczPkbuievC8lvJ4erny8ZzP1y7nf8Zbp0hKiAkC/oX1qmnkZRM5Eov6P64scW5KtnnR04tU0zQbeX30BHNvkfDoFyRh/44w7q8OCOZUav9cbqx24S4JSIEz/LWbQ/QnMq+azrKLPXOZToQy2teCfKFYhrfOzK7Eq+WWaV6Kqa55p0O3q4QmXvO/zeMhOVbT1++HzE=
